version: "3.4"

services:

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  scraper:
    build: ./scraper
    links:
      - mongo
      - redis

  parser:
    build: ./parser
    links:
      - mongo
      - redis
