version: "3"

services:
  scraper:
     build: .
     image: "myscraper"
  redis:
    image: "redis"
    ports:
      - "6397:6397"
    mongo:
      image: "mongo"
      ports:
        - "27017:27017"
